[package]
name = "md5sumsum"
version = "0.2.0"
authors = ["Clément Depraz"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
rust-crypto = "0.2.36"
rustc-serialize = "0.3"